<?php

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function password_generator_form_user_register_form_alter(&$form, &$form_state, $form_id) {  
  // Rearrange the order of elements to place 'notify new user'
  // checkbox above the password.
  $form['account']['mail']['#weight'] = -8;
  $form['account']['notify']['#weight'] = -5;
  $form['account']['notify']['#title'] = t('Notify user of new account and send one-time login link.');
  
  // Set default notify value to 1 and toggle password field
  $form['account']['notify']['#default_value'] = TRUE;
  
  // States doesn't seem to work on fields of type pass_confirm,
  // so let's wrap it in a container
  $form['account']['pass_container'] = array(
    '#type' => 'container',
    '#weight' => -4,
    '#states' => array(
      'visible' => array(
        ':input[name="notify"]' => array('checked' => FALSE),
      ),
    ),
    'pass' => empty($form['account']['pass']) ? array('#required' => FALSE) : $form['account']['pass'],
  );
  unset($form['account']['pass']);
  
  // We have to remove the #required requirement, or else our
  // validation function never gets called.
  unset($form['account']['pass_container']['pass']['#required']);
  array_unshift($form['#validate'], 'password_generator_form_validate');
}

/**
 * Form validation function for user_register_form.
 */
function password_generator_form_validate($form, &$form_state) {
  // The form api handles most errors for the pass_confirm field type, but since
  // we've removed the required condition, we have to ensure that we set an interim password
  // only if the notify field is also set. Otherwise we complain of an empty password.
  if (empty($form_state['values']['pass']) && $form_state['values']['notify'] == 1) {
    $password = _password_generate_password();
    form_set_value($form['account']['pass_container']['pass'], $password, $form_state);
  }
  else if (empty($form_state['values']['pass'])) {
    form_set_error('pass', 'Password field is required if you are not notifying user by email.');
  }
}

/**
 * Generate random password.
 *
 * rand() isn't truly random and 89999 passwords is a small number,
 * so this is not a secure form of password generation.
 * Since this is only for very short-term passwords it is acceptable.
 */
function _password_generate_password() {
  return md5(rand(10000, 99999));
}
